version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=snip
      - POSTGRES_PASSWORD=snip
      - POSTGRES_DB=snip
  cache:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass snip
